version: '3.9'

services:
  narco-backend-api-v1:
    image: narco-backend-api:17.11.29
    container_name: narco-backend-v1
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - .:/app
    restart: unless-stopped
    ports:
      - '${PORT}:${PORT}'
    networks:
      - narco-network
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      BASE_URL: ${BASE_URL}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      JWT_EXPIRE_TIME: ${JWT_EXPIRE_TIME}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      TWILIO_SID: ${TWILIO_SID}

networks:
  narco-network:
    external: true