version: '3.9'

services:
  narco-backend-api-v1:
    image: narco-backend-api:17.11.29
    container_name: narco-backend-v1
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - .:/app
    restart: unless-stopped
    ports:
      - '${PORT}:${PORT}'
    networks:
      - narcolepsy_network
    env_file:
      - .env

networks:
  narcolepsy_network:
    external: true