version: "3.9"

services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    volumes:
      - /var/docker/mariadb/conf:/etc/mysql
    ports:
      - "3306:3306"
    networks:
      - narco-network
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    ports:
      - "8183:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: always
    networks:
      - narco-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9091:9091"
      - "9099:9099"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
    volumes:
      - minio_storage:/data
    networks:
      - narco-network
    command: server --address ":9099" --console-address ":9091" /data
    restart: always

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # HTTP management UI
    volumes:
      - /etc/letsencrypt/live/ondergrup.hidirektor.com.tr:/certs
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - narco-network
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    command: [ "redis-server", "--include", "/etc/redis/redis.conf" ]
    networks:
      - narco-network
    restart: always

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    depends_on:
      - redis
      - graph
      - search
      - timeseries
    ports:
      - "5540:5540"
    networks:
      - narco-network
    volumes:
      - redis_insight_volume_data:/db

  graph:
    image: redislabs/redisgraph
    container_name: redis_graph
    ports:
      - "6380:6379"
    restart: always
    networks:
      - narco-network

  search:
    image: redislabs/redisearch:latest
    container_name: redis_search
    ports:
      - "6381:6379"
    restart: always
    networks:
      - narco-network

  timeseries:
    image: redislabs/redistimeseries
    container_name: redis_timeseries
    ports:
      - "6382:6379"
    restart: always
    networks:
      - narco-network

volumes:
  minio_storage: { }
  redis_volume_data: { }
  redis_insight_volume_data: { }

networks:
  narco-network:
    external: true